# # Database Configuration (using H2 in-memory)
# spring.datasource.url=jdbc:h2:mem:apartment_db;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# # JPA / Hibernate Configuration
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true


spring.application.name=ams
server.servlet.context-path=/api
server.port=8080
# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ams_project;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123


# Spring Data JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary Configuration
cloudinary.cloud-name=rir6b8kp
cloudinary.api-key=158885599554128
cloudinary.api-secret=rFOptSpSygPIHYYhpRZPv93zXY0

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
